application: flashcards-ench
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /lib
  static_dir: lib
- url: /js
  static_dir: js

- url: /.*
  script: flashcards.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest